/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as authChooseOrganizationRouteImport } from './routes/(auth)/choose-organization'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as LiveblocksAuthRouteImport } from './routes/liveblocks/auth'
import { Route as dashboardWorkflowsIdIndexRouteImport } from './routes/(dashboard)/workflows/$id/index'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const authChooseOrganizationRoute = authChooseOrganizationRouteImport.update({
  id: '/choose-organization',
  path: '/choose-organization',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const LiveblocksAuthRoute = LiveblocksAuthRouteImport.update({
  id: '/liveblocks/auth',
  path: '/liveblocks/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardWorkflowsIdIndexRoute =
  dashboardWorkflowsIdIndexRouteImport.update({
    id: '/workflows/$id/',
    path: '/workflows/$id/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/choose-organization': typeof authChooseOrganizationRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/liveblocks/auth': typeof LiveblocksAuthRoute
  '/': typeof dashboardIndexRoute
  '/workflows/$id/': typeof dashboardWorkflowsIdIndexRoute
}
export interface FileRoutesByTo {
  '/choose-organization': typeof authChooseOrganizationRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/liveblocks/auth': typeof LiveblocksAuthRoute
  '/': typeof dashboardIndexRoute
  '/workflows/$id': typeof dashboardWorkflowsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/(auth)/choose-organization': typeof authChooseOrganizationRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/liveblocks/auth': typeof LiveblocksAuthRoute
  '/(dashboard)/': typeof dashboardIndexRoute
  '/(dashboard)/workflows/$id/': typeof dashboardWorkflowsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/choose-organization'
    | '/sign-in'
    | '/sign-up'
    | '/liveblocks/auth'
    | '/'
    | '/workflows/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/choose-organization'
    | '/sign-in'
    | '/sign-up'
    | '/liveblocks/auth'
    | '/'
    | '/workflows/$id'
  id:
    | '__root__'
    | '/(auth)'
    | '/(dashboard)'
    | '/(auth)/choose-organization'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/liveblocks/auth'
    | '/(dashboard)/'
    | '/(dashboard)/workflows/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  LiveblocksAuthRoute: typeof LiveblocksAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/choose-organization': {
      id: '/(auth)/choose-organization'
      path: '/choose-organization'
      fullPath: '/choose-organization'
      preLoaderRoute: typeof authChooseOrganizationRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/liveblocks/auth': {
      id: '/liveblocks/auth'
      path: '/liveblocks/auth'
      fullPath: '/liveblocks/auth'
      preLoaderRoute: typeof LiveblocksAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/workflows/$id/': {
      id: '/(dashboard)/workflows/$id/'
      path: '/workflows/$id'
      fullPath: '/workflows/$id/'
      preLoaderRoute: typeof dashboardWorkflowsIdIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authChooseOrganizationRoute: typeof authChooseOrganizationRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authChooseOrganizationRoute: authChooseOrganizationRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface dashboardRouteRouteChildren {
  dashboardIndexRoute: typeof dashboardIndexRoute
  dashboardWorkflowsIdIndexRoute: typeof dashboardWorkflowsIdIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardWorkflowsIdIndexRoute: dashboardWorkflowsIdIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  LiveblocksAuthRoute: LiveblocksAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
